services:
  - type: web
    name: livepoll
    env: node
    plan: free
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
